# Generated by Django 4.2.18 on 2025-02-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipodeatividade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodeatividade',
            name='codigo',
            field=models.AutoField(help_text='Código do Tipo de atividade', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipodeatividade',
            name='descricao',
            field=models.CharField(help_text='Informe a descrição do Tipo de atividade', max_length=100),
        ),
    ]
