# Generated by Django 4.2.18 on 2025-02-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('codigo', models.AutoField(help_text='Código do Titulo', primary_key=True, serialize=False)),
                ('descricao', models.CharField(help_text='Informe a descrição do Titulo', max_length=100)),
            ],
        ),
    ]
