# Generated by Django 4.2.18 on 2025-02-14 23:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0001_initial'),
        ('instrutor', '0001_initial'),
        ('tipodeatividade', '0002_alter_tipodeatividade_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('numero', models.AutoField(help_text='Informe a turma do Aluno', primary_key=True, serialize=False)),
                ('horario_aula', models.TimeField(help_text='Informe a hora em que a hora da aula da Turma')),
                ('duracao_aula', models.SmallIntegerField(default=30, help_text='Informe a duração da aula da Turma')),
                ('data_inicial', models.DateField(default=datetime.datetime(2025, 2, 14, 23, 43, 54, 317924, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial da Turma')),
                ('data_final', models.DateField(default=datetime.datetime(2025, 2, 14, 23, 43, 54, 317924, tzinfo=datetime.timezone.utc), help_text='Informe a data final da Turma')),
                ('codigo_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipodeatividade.tipodeatividade')),
                ('id_instrutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instrutor.instrutor')),
                ('matricula_monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aluno.aluno')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='TurmaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_matricula', models.DateField(default=django.utils.timezone.now, help_text='Numero Matrícula do aluno')),
                ('data_fim_matricula', models.DateField(blank=True, help_text='Data Fim Matrícula do aluno', null=True)),
                ('matricula_aluno', models.ForeignKey(help_text='Matrícula do Aluno', on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
                ('turma_numero', models.ForeignKey(help_text='Número da Turma', on_delete=django.db.models.deletion.CASCADE, to='turma.turma')),
            ],
        ),
    ]
