# Generated by Django 4.2.18 on 2025-02-14 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='data_final',
            field=models.DateField(default=datetime.datetime(2025, 2, 14, 23, 52, 29, 109939, tzinfo=datetime.timezone.utc), help_text='Informe a data final da Turma'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_inicial',
            field=models.DateField(default=datetime.datetime(2025, 2, 14, 23, 52, 29, 109939, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial da Turma'),
        ),
    ]
