# Generated by Django 4.2.18 on 2025-02-14 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0002_alter_turma_data_final_alter_turma_data_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='data_final',
            field=models.DateField(default=datetime.datetime(2025, 2, 14, 23, 54, 7, 70414, tzinfo=datetime.timezone.utc), help_text='Informe a data final da Turma'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_inicial',
            field=models.DateField(default=datetime.datetime(2025, 2, 14, 23, 54, 7, 70414, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial da Turma'),
        ),
    ]
