# Generated by Django 4.2.18 on 2025-02-15 00:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_alter_aluno_data_inicial'),
        ('turma', '0003_alter_turma_data_final_alter_turma_data_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='data_final',
            field=models.DateField(default=datetime.datetime(2025, 2, 15, 0, 27, 0, 627427, tzinfo=datetime.timezone.utc), help_text='Informe a data final da Turma'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_inicial',
            field=models.DateField(default=datetime.datetime(2025, 2, 15, 0, 27, 0, 627427, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial da Turma'),
        ),
        migrations.CreateModel(
            name='Ausencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ausencia', models.DateField(default=django.utils.timezone.now, help_text='Data falta do aluno')),
                ('matricula_aluno', models.ForeignKey(help_text='Matrícula do Aluno', on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
                ('turma_numero', models.ForeignKey(help_text='Número da Turma', on_delete=django.db.models.deletion.CASCADE, to='turma.turma')),
            ],
        ),
    ]
