# Generated by Django 4.2.18 on 2025-02-15 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0004_alter_turma_data_final_alter_turma_data_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='data_final',
            field=models.DateField(default=datetime.datetime(2025, 2, 15, 0, 28, 43, 865672, tzinfo=datetime.timezone.utc), help_text='Informe a data final da Turma'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_inicial',
            field=models.DateField(default=datetime.datetime(2025, 2, 15, 0, 28, 43, 865672, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial da Turma'),
        ),
    ]
